name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.6.0
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::728291782722:role/iamrole-aws-action
          role-session-name: MySessionName
      - run: aws sts get-caller-identity